name: Build 
on: 
  workflow_dispatch:
jobs:
  mkdebs:
    runs-on: ubuntu-latest
    steps:
      - name: Download Git
        run: |
          sudo apt update
          sudo apt install git
          git clone https://github.com/MatuushOS/Repo
      - name: Setup Makedeb, change directory to the repo and build Picom, Una and OMP
        run: |
          wget -qO - 'https://proget.makedeb.org/debian-feeds/makedeb.pub' | gpg --dearmor | sudo tee /usr/share/keyrings/makedeb-archive-keyring.gpg 1> /dev/null
          echo 'deb [signed-by=/usr/share/keyrings/makedeb-archive-keyring.gpg arch=all] https://proget.makedeb.org/ makedeb main' | sudo tee /etc/apt/sources.list.d/makedeb.list    
          sudo apt update
          sudo apt install makedeb
          cd $(pwd)/picom-jonaburg-git
          makedeb -sA
          cd $(pwd)/una
          makedeb -sA
          cd $(pwd)/oh-my-posh
          makedeb -sA
