name: Build 
on: 
  workflow_dispatch:
jobs:
  mkdebs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Makedeb, change directory to the repo and build Picom, Una and OMP
        run: |
          # Set the makedeb release you want.
          export MAKEDEB_RELEASE='makedeb'

          # Run the install script. Note that it's `bash -c` and not `bash -ci` now.
          bash -c "$(wget -qO - 'https://shlink.makedeb.org/install')"
          cd ~/Repo/picom-jonaburg-git
          makedeb -sA
          cd ~/Repo/una
          makedeb -sA
          cd ~/Repo/oh-my-posh
          makedeb -sA
